version: '0.2'
language: en
words:
- altera
- bazelisk
- bazelrc
- bazelversion
- beautysh
- bugprone
- Constexpr
- cppcheck
- cppcoreguidelines
- cpplint
- cxxopt
- DCMAKE
- EDITMSG
- frontmatter
- Gisler
- hdrs
- hedron
- Hedron's
- hicpp
- includeorder
- Isrc
- iwyu
- lgisler
- libc
- libcxx
- libtinfo5
- linelength
- llvmlibc
- mdformat
- oclint
- pyenv
- pyproject
- srcs
- standardcfirst
- statecharts
- stdarg
- uncrustify
- virtualenv
- Wcast
- Wconversion
- Werror
- Wextra
- Wformat
- Wnon
- Wshadow
- Wsign
- Wunused
