version: '0.2'
language: en
words:
- beautysh
- cppcheck
- cpplint
- cxxopt
- DCMAKE
- EDITMSG
- frontmatter
- Gisler
- hdrs
- hedron
- Hedron's
- Isrc
- iwyu
- lgisler
- llvmlibc
- mdformat
- oclint
- pyenv
- pyproject
- srcs
- statecharts
- uncrustify
- virtualenv
- Wcast
- Wconversion
- Werror
- Wextra
- Wformat
- Wnon
- Wshadow
- Wsign
- Wunused
