load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "cpp_statecharts",
    hdrs = glob(["include/cpp_statecharts/*.hpp"],),
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
)
