load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "cpp_statecharts",
    hdrs = ["include/cpp_statecharts/cpp_statecharts.hpp",],
    includes = ["include"],
    visibility = [
        "//src/examples:__pkg__",
    ],
)
