name: pre-commit

on:
  push:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install C++ tools and dependencies
        run: |
          # Install C++ analysis tools
          sudo apt-get update
          sudo apt-get install -y cppcheck include-what-you-use

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@v0.8.1
        with:
          # Optional: Pin to specific Bazel version
          bazelisk-version: "1.22.1"

      - name: Generate compilation database
        run: |
          # Generate compile_commands.json for clang-tidy
          bazel run @hedron_compile_commands//:refresh_all

      - name: Install pre-commit and dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure
